services:
  - type: web
    name: tcg-card-price-bot
    runtime: node
    plan: starter  # or whatever plan you're using
    buildCommand: |
      npm ci
      npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/.cache/puppeteer
    disk:
      name: puppeteer-cache
      mountPath: /opt/render/project/.cache
      sizeGB: 2
